name: sales
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
    # version: ^0.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  badges: ^3.0.2

  cloud_firestore: ^4.2.0
  cached_network_image: ^3.2.1

  dartz: ^0.10.1
  equatable: ^2.0.3


  file_picker: ^5.3.2
  firebase_core_platform_interface: ^4.5.2
  firebase_auth: ^4.2.0
  firebase_storage: ^11.0.7
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  font_awesome_flutter: ^10.3.0
  fluttertoast: ^8.0.8
  flutter_staggered_grid_view: ^0.6.1
  flutter_dotenv: ^5.0.2
  flutter_countdown_timer: ^4.1.0
  

  google_mlkit_object_detection: ^0.6.0
  google_mlkit_text_recognition: ^0.5.0
  google_maps_flutter: ^2.1.6
  google_fonts: ^4.0.3
  geocoding: ^2.0.4

  http: ^1.0.0

  image_picker: ^0.8.5+3
  image_cropper: ^5.0.0
  infinite_scroll_pagination: ^3.2.0

  lottie: ^2.0.0
  location: ^4.4.0


  pin_code_fields: ^7.3.0
  path_provider: ^2.0.10
  photo_view: ^0.14.0
  pull_to_refresh_flutter3: ^2.0.1
  

  rxdart: ^0.27.4

  shimmer: ^2.0.0
  share_plus: ^7.0.2
  shared_preferences: ^2.0.15
  syncfusion_flutter_pdfviewer: ^22.1.38

  timeago: ^3.2.2
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
  api:
    path: ../../pkg/api
  common:
    path: ../../pkg/common
  simple_logger: ^1.9.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
