name: Category Service
on:
  push:
    paths: ['backend/go/api/category/**', '.github/workflows/category.yml','backend/go/pkg/**']
jobs:
   build-and-deploy:
    if: ${{ (github.ref == 'refs/heads/develop') }}
    runs-on: ubuntu-latest  
    environment: develop
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
          token_format: access_token

      - name: Build service
        run: |
            (cd ./backend/go/api/category && make build)
            gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
            docker tag category-service:latest asia-southeast2-docker.pkg.dev/dairy-food-development/images/backend/go/api/category-service:v1.0.0
            docker push asia-southeast2-docker.pkg.dev/dairy-food-development/images/backend/go/api/category-service:v1.0.0

      - name: Deploy Service
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'category-service'
          region: 'asia-southeast2'
          image: 'asia-southeast2-docker.pkg.dev/dairy-food-development/images/backend/go/api/category-service:v1.0.0' 
          project_id: 'dairy-food-development'  
          secrets:  |
            DB_URI=category-service:latest
   build-and-deploy-production:
    if: ${{ (github.ref == 'refs/heads/production') }} 
    runs-on: ubuntu-latest  
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
          token_format: access_token

      - name: Build service
        run: |
            (cd ./backend/go/api/category && make build)
            gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
            docker tag category-service:latest asia-southeast2-docker.pkg.dev/dairy-food-production/backend/go/api/category-service:v1.0.0
            docker push asia-southeast2-docker.pkg.dev/dairy-food-production/backend/go/api/category-service:v1.0.0

      - name: Deploy Service
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'category-service'
          region: 'asia-southeast2'
          image: 'asia-southeast2-docker.pkg.dev/dairy-food-production/backend/go/api/category-service:v1.0.0' 
          project_id: 'dairy-food-production'
          secrets:  |
            DB_URI=category-service:latest